# Generated by Django 3.1.12 on 2025-06-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250609_0739'),
        ('app', '0007_chathistory'),
    ]

    operations = [
    ]
